=== Vladyslav-Frolov/javaCodeLib/src/main/java/info/vladyslav/codeLibrary/u03web/web02xml/xml_01_dtd/students.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ENTITY elementGroup "name, telephone, address">

        <!ELEMENT students (student)+>
        <!ELEMENT student (%elementGroup;)>
        <!ATTLIST student
                login ID #REQUIRED
                faculty CDATA #REQUIRED
                >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT address (country, city, street)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>

=== Vladyslav-Frolov/javaCodeLib/javaBasics/src/main/java/info/vladyslav/cl/javaBasics/u03web/web02xml/xml_01_dtd/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM
        "D:\Documents\Workspace\myCodeLib\javaMain\javaBasics\src\main\java\info\vladyslav\cl\javaBasics\u03web\web02xml\xml_01_dtd\students.dtd">
<students>
    <student login="MitarAlex7" faculty="mmf">
        <name>Mitar Alex</name>
        <telephone>2456474</telephone>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Kalinovsky 45</street>
        </address>
    </student>
    <student login="Pashkin5" faculty="mmf">
        <name>Pashkin Alex</name>
        <telephone>3453789</telephone>
        <address>
            <country>Belarus</country>
            <city>Brest</city>
            <street>Knorina 56</street>
        </address>
    </student>
</students>
